.
----------------------------------------------------------------------
Ran 1 test in 1.250s

OK
.....FF
======================================================================
FAIL: test_null_characters (rnvs_tb.blocks.block2.QOTDServerTestCase)
Test the servers handling of special characters like a null byte.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rnvs_tb/common.py", line 32, in log_wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rnvs_tb/blocks/block2.py", line 169, in test_null_characters
    msg='No response from server received in time!')
AssertionError: False is not true : No response from server received in time!

======================================================================
FAIL: test_one_line (rnvs_tb.blocks.block2.QOTDServerTestCase)
Test the servers ability to serve a simple quote from a file, while accepting extra newline and null bytes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rnvs_tb/common.py", line 32, in log_wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rnvs_tb/blocks/block2.py", line 105, in test_one_line
    self.assertTrue(ready, msg=f'Server did not open port 17 within {self.startupTimeout} seconds after starting')
AssertionError: False is not true : Server did not open port 17 within 3.0 seconds after starting

----------------------------------------------------------------------
Ran 7 tests in 25.589s

FAILED (failures=2)
